name: de-escalate
favicon: null
layout_spectrum: 0.963753558229655
typography_spectrum: 0.4895855525974184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3609336232766509
  lightness: 0.7277731820940971
  saturation: 0.755327221704647
  rhythmicContrast: 0.7156980179715902
purpose: []
